import FWCore.ParameterSet.Config as cms

process = cms.Process("ANALYSIS")

#PDG IDs
A_PDGID = 36
Z_PDGID = 23
W_PDGID = 24
TAU_PDGID = 15
MU_PDGID = 13
NUMU_PDGID = 14
D_PDGID = 1
U_PDGID = 2
S_PDGID = 3
C_PDGID = 4
B_PDGID = 5
T_PDGID = 6
G_PDGID = 21
ANY_PDGID = 0

#tau decay types
TAU_HAD = 0
TAU_MU = 1
TAU_E = 2
TAU_ALL = 3

#tau hadronic decay types
TAU_ALL_HAD = -1
TAU_1PRONG_0NEUTRAL = 0
TAU_1PRONG_1NEUTRAL = 1
TAU_1PRONG_2NEUTRAL = 2
TAU_1PRONG_3NEUTRAL = 3
TAU_1PRONG_NNEUTRAL = 4
TAU_2PRONG_0NEUTRAL = 5
TAU_2PRONG_1NEUTRAL = 6
TAU_2PRONG_2NEUTRAL = 7
TAU_2PRONG_3NEUTRAL = 8
TAU_2PRONG_NNEUTRAL = 9
TAU_3PRONG_0NEUTRAL = 10
TAU_3PRONG_1NEUTRAL = 11
TAU_3PRONG_2NEUTRAL = 12
TAU_3PRONG_3NEUTRAL = 13
TAU_3PRONG_NNEUTRAL = 14
TAU_RARE = 15

#no consideration of pT rank
ANY_PT_RANK = -1

process.load("FWCore.MessageService.MessageLogger_cfi")
process.MessageLogger.cerr.FwkReport.reportEvery = cms.untracked.int32(100)

process.options = cms.untracked.PSet(wantSummary = cms.untracked.bool(True))

process.maxEvents = cms.untracked.PSet( input = cms.untracked.int32(-1) )

readFiles = cms.untracked.vstring()
process.source = cms.Source(
    "PoolSource",
    fileNames = readFiles,
    skipEvents = cms.untracked.uint32(0)
    )
## readFiles.extend([
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_1000_3_TDu.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_100_1_o2D.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_101_1_FI0.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_102_1_wM7.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_103_1_IFm.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_104_1_Y6u.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_105_1_HYt.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_106_1_tbV.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_107_1_aTc.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_108_1_FHP.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_109_1_G26.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_10_1_Ui0.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_110_1_5nP.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_111_1_Eav.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_112_1_jhv.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_113_1_A0f.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_114_1_MXl.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_115_1_LNJ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_119_1_piV.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_11_1_cB9.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_120_1_iwq.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_12_1_3nx.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_13_1_zxZ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_14_1_LUE.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_15_1_aa6.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_16_1_uPm.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_17_1_ZqK.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_18_1_uDP.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_19_1_X7R.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_1_1_EeD.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_20_1_rPJ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_21_1_VWc.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_22_1_W1T.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_23_1_moa.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_24_1_Jbp.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_25_1_Nh9.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_26_1_cAt.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_27_1_PUv.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_28_1_3lh.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_29_1_PpY.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_2_1_NDZ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_30_1_j0D.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_31_1_JKQ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_32_1_F5c.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_33_1_3Qa.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_34_1_9Ez.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_35_1_gXQ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_36_1_D1N.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_37_1_uUR.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_38_1_l3p.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_39_1_vhE.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_3_1_D6F.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_401_1_oCz.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_402_1_9hJ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_404_1_UaO.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_405_1_xbB.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_406_1_tUY.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_407_1_eTh.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_408_1_boP.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_409_1_kAD.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_40_1_4NC.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_410_1_Msg.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_411_1_60F.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_412_1_WQq.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_413_1_SIq.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_414_1_1Le.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_415_1_7xr.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_416_1_vMy.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_417_1_jjN.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_418_1_5CY.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_419_1_vYw.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_41_1_MlB.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_420_1_twA.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_421_1_1m4.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_422_1_yWs.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_423_1_0NS.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_424_1_mW8.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_425_1_yY4.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_426_1_i3m.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_427_1_6DW.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_428_1_BIs.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_429_1_fVN.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_42_1_3Is.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_430_1_2FV.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_431_1_JKA.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_432_1_Nsr.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_433_1_Dq6.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_434_1_xsU.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_435_1_PCc.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_437_1_7N5.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_438_1_FRe.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_439_1_BMY.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_43_1_cQp.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_440_1_t0F.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_441_1_tMP.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_442_1_QQD.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_443_1_1BD.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_444_1_nmX.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_445_1_fSl.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_446_1_Srx.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_447_1_zk0.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_448_1_JVr.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_44_1_GAs.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_450_1_HcO.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_451_1_o61.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_452_1_FZF.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_453_1_KBc.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_454_1_t5o.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_455_1_tB8.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_456_1_Ppz.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_457_1_ycb.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_458_1_zgt.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_459_1_t42.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_45_1_YHf.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_460_1_F8A.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_461_1_xQc.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_462_1_Bem.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_463_1_sz5.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_464_1_g0g.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_465_1_oOx.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_466_1_Evz.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_467_1_O9t.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_468_1_0gj.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_469_1_7EF.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_46_1_kdf.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_470_1_iTH.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_471_1_FBT.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_472_1_P1D.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_473_1_nsl.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_474_1_DsA.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_475_1_g5V.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_476_1_cC2.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_477_1_3Mv.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_478_1_aMN.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_479_1_0gh.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_47_1_bNv.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_480_1_wjr.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_481_1_f2u.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_482_1_Tsx.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_483_1_fxF.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_484_1_FzS.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_485_1_aE3.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_486_1_pLU.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_487_1_A6g.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_489_1_PYs.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_48_1_xjA.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_490_1_e0W.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_491_1_DKT.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_493_1_DQc.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_494_1_S3B.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_495_1_4Cf.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_496_1_x0x.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_497_1_Km9.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_498_1_xJJ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_499_1_yDH.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_49_1_XG9.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_4_1_8q0.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_500_1_FdG.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_501_2_1vi.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_502_2_Gd4.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_503_2_4IT.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_504_2_r5W.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_505_2_6EE.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_506_2_5sw.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_507_2_1PO.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_508_2_HLT.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_509_2_UP0.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_50_1_QvS.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_510_2_Kq7.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_511_2_Fpx.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_512_2_VG9.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_513_2_61f.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_514_2_UpQ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_515_2_Q9H.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_516_2_sjb.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_517_2_Vf1.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_518_2_KBP.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_519_2_8o5.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_51_1_BR8.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_520_2_qdm.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_521_2_Qif.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_522_2_fuo.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_523_2_E4i.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_524_2_Ktb.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_525_2_hgc.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_526_2_nYm.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_527_2_ykf.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_528_2_wbA.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_529_2_Qsn.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_52_1_7Rl.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_530_2_9n5.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_531_2_Jf6.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_532_2_Ygs.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_533_2_ygi.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_534_2_Z4b.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_535_2_rfb.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_536_2_xuD.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_537_2_cyQ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_538_2_NeB.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_539_2_GLI.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_53_1_Sii.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_540_2_dWA.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_541_2_lma.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_542_2_RrX.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_543_2_0MB.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_544_2_6kz.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_545_2_Zc4.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_546_2_5t7.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_547_2_mYL.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_548_2_Hel.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_549_2_Irc.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_54_1_Ghx.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_550_2_oxe.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_551_2_qnf.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_552_2_Uuq.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_553_2_bh6.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_554_2_vpK.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_555_2_yq8.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_556_2_pMj.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_557_2_52b.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_558_2_FNL.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_559_2_ze3.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_55_1_gvB.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_560_2_hoM.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_561_2_GB8.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_562_2_FaP.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_563_2_4e8.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_564_2_NqE.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_565_2_Gf0.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_566_2_k2J.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_567_2_bGb.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_568_2_AO2.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_569_2_jpV.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_56_1_ah6.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_570_2_8Uu.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_571_2_lz0.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_572_2_qBB.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_573_2_hau.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_574_2_5pU.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_575_2_rLY.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_576_2_j09.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_577_2_mZo.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_578_2_VlL.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_579_2_MSp.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_57_1_9DU.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_580_2_bjC.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_581_2_ZJ0.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_582_2_0e7.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_583_2_JNq.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_584_2_UDl.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_585_2_KXe.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_586_2_WtD.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_587_1_PAF.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_588_1_0LP.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_589_1_q8a.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_58_1_ZTs.root'
##     ])
## readFiles.extend([
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_590_2_yEq.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_591_2_SEv.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_592_1_9FO.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_593_1_akT.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_594_1_2XR.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_595_3_lZg.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_596_4_29d.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_597_3_I9W.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_598_3_ylY.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_599_3_hap.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_59_1_Hkl.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_5_1_A8E.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_600_2_31u.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_601_2_7Lg.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_602_2_eP5.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_603_2_9rX.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_604_2_KFl.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_605_2_Dey.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_606_2_knD.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_607_2_Sjd.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_608_2_lrJ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_609_2_MNQ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_60_1_3pz.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_610_2_Sem.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_611_2_NFy.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_612_2_AGn.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_613_2_oPW.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_614_2_Ny4.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_615_2_iwl.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_616_2_Mrb.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_617_2_X1x.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_618_2_5zd.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_619_2_C1w.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_61_1_V0i.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_620_2_5l3.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_621_2_5jJ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_622_2_6Os.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_623_2_D5j.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_624_2_36H.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_625_2_D3N.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_626_2_kMl.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_627_2_qBx.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_628_2_iwI.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_629_2_9SA.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_62_1_RHv.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_630_2_SqM.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_631_2_9vA.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_632_2_6EX.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_633_2_AMU.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_634_2_SzO.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_635_2_kmk.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_636_2_wSU.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_637_2_WWb.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_638_2_YJK.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_639_1_KE5.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_63_1_j0f.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_640_2_7d1.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_641_2_5Ff.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_642_2_tHl.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_643_2_pJa.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_644_2_gi2.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_645_2_p9d.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_646_3_rYj.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_647_3_Jtl.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_648_3_aqt.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_649_3_BWf.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_64_1_Foi.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_650_2_s8A.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_651_3_fPK.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_652_2_60O.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_653_3_1eV.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_654_3_YOa.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_655_3_gEf.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_656_4_isv.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_657_3_iX4.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_658_3_Plk.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_659_2_YQT.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_65_1_LPJ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_660_3_nVf.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_661_3_equ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_662_2_agU.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_663_2_Fgf.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_664_3_2br.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_665_2_1oU.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_666_4_yeo.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_667_2_AvX.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_668_2_oZx.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_669_2_H8o.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_66_1_tDH.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_670_2_Ybh.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_671_2_Geo.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_672_2_JVh.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_673_2_RDc.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_674_2_3OX.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_675_2_RI2.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_676_2_U7B.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_677_2_meG.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_678_2_0vm.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_679_2_SJx.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_67_1_oQ5.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_680_2_wxG.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_681_2_1OD.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_682_3_3EG.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_683_2_NoJ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_684_2_473.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_685_2_Ptw.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_686_2_Txl.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_687_2_4S3.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_688_2_iHN.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_689_2_IOf.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_68_1_lKV.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_690_2_fkB.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_691_2_Muv.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_692_2_3tL.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_693_2_AJ9.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_694_2_50J.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_695_2_ByS.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_696_2_WDY.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_697_2_FN1.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_698_2_Sxk.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_699_2_ZPu.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_69_1_TLy.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_6_1_KRD.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_700_3_LOX.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_701_3_Ir7.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_702_3_L4e.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_703_2_p8p.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_704_3_BsM.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_705_3_EaJ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_706_2_Y9P.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_707_2_DDh.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_708_2_YLJ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_709_2_YeA.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_70_1_4Tt.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_710_3_FvH.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_711_2_AOE.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_712_2_gnX.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_713_3_iKU.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_714_2_QHG.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_715_2_4aJ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_716_2_DzC.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_717_2_ejV.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_718_2_UJV.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_719_2_l0a.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_71_1_XWV.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_720_2_5jJ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_721_2_d4y.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_722_2_CNI.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_723_2_c1n.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_724_2_MPl.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_725_2_Vec.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_726_2_fZX.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_727_2_QG0.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_728_2_s78.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_729_2_pqr.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_72_1_fNM.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_730_2_Qcy.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_731_2_qtX.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_732_2_ZZg.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_733_2_kfd.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_734_2_Cun.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_735_2_QTl.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_736_2_04g.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_737_2_pq8.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_738_2_cJt.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_739_2_Yea.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_73_1_lDm.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_740_2_8Oq.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_741_2_Kda.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_742_2_Uov.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_743_2_783.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_744_2_ZCd.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_745_2_n3f.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_746_2_Fxn.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_747_2_Sru.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_748_2_6Mu.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_749_2_9G2.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_74_1_C0X.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_750_2_wpt.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_751_2_WMQ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_752_2_HEQ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_753_2_TSC.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_754_2_ZTp.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_755_2_Lyw.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_756_2_mik.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_757_3_yF8.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_758_3_0H0.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_759_3_Hc9.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_75_1_pLe.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_760_2_EzA.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_761_2_m0D.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_762_2_D0r.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_763_3_nB6.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_764_3_Jr7.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_765_3_ynL.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_766_3_qJZ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_767_3_edI.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_768_3_kh1.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_769_3_9rK.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_76_1_lSY.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_770_3_eb8.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_771_3_nIp.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_772_3_cfM.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_773_3_mF5.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_774_3_Ov4.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_775_2_QjN.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_776_3_hdP.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_777_2_1KI.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_778_3_RTE.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_779_2_3Zg.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_77_1_UzR.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_780_3_19V.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_781_3_1lY.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_782_3_GMx.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_783_3_ULA.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_784_2_zXA.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_785_3_uXK.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_786_3_Br0.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_787_2_HSU.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_788_2_mvX.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_789_2_j8x.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_78_1_FWU.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_790_3_dgD.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_791_2_a6D.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_792_3_ewf.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_793_2_HxR.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_794_2_mVM.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_795_2_Vcg.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_796_3_TG3.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_797_3_2ht.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_798_2_E32.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_799_2_gES.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_79_1_eL7.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_7_1_ZPm.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_800_2_1Rw.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_801_2_2Cp.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_802_2_O1j.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_803_2_G7F.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_804_3_CC0.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_805_2_n7f.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_806_2_CEf.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_807_3_zQc.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_808_3_t3k.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_809_3_9iP.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_80_1_ke1.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_810_2_mSr.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_811_3_8DH.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_812_3_Aov.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_813_3_JKv.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_814_3_YkB.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_815_3_H6l.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_816_3_FCR.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_817_3_ZNb.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_818_3_jEC.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_819_3_yVK.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_81_1_NrP.root'
##     ])
## readFiles.extend([
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_820_3_zSv.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_821_3_Vj2.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_822_3_Vsj.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_823_3_jqO.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_824_2_M48.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_825_2_mgB.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_826_3_YDx.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_827_3_h6R.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_828_2_UK8.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_829_2_G1D.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_82_1_eGL.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_830_2_4vI.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_831_3_jcK.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_832_3_hLf.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_833_2_YY4.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_834_2_asr.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_835_3_wud.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_836_3_pnf.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_837_2_Mv6.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_838_2_D0J.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_839_2_Dai.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_83_1_1XX.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_840_3_tEb.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_841_2_jKS.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_842_2_qZy.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_843_2_e5X.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_844_2_WAy.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_845_2_USn.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_846_2_3Oq.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_847_2_kIj.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_848_2_hVR.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_849_2_nxR.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_84_1_6VL.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_850_2_EqI.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_851_2_ANV.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_852_2_Xkr.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_853_2_5YJ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_854_2_zAR.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_855_2_ucl.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_856_2_RCK.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_857_2_7hb.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_858_2_9MS.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_859_2_LJa.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_860_2_oVr.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_861_2_laY.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_862_2_2ai.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_863_2_ZIJ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_864_2_YdI.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_865_2_Puk.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_866_3_hWt.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_867_2_Quo.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_868_2_WET.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_869_2_QDW.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_86_1_bl9.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_870_3_SwK.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_871_2_9PS.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_872_2_L97.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_873_3_IJu.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_874_2_QVF.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_875_2_on4.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_876_2_g4m.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_877_2_xh3.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_878_2_Y9Q.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_879_2_9Vh.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_87_1_KmI.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_880_3_tue.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_881_3_4wX.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_882_2_Pyw.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_883_2_GWA.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_884_2_VSr.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_885_2_oEx.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_886_2_1MC.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_887_2_Xps.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_888_2_k2R.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_889_2_LYx.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_88_1_SIQ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_890_2_ODp.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_891_2_jzX.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_892_3_lIR.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_893_2_ooP.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_894_2_Sdh.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_895_4_dag.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_896_2_iUl.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_897_2_tAu.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_898_2_yZ1.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_899_2_6DB.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_89_1_0SG.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_8_1_nzv.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_900_2_HtS.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_901_1_T9c.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_902_1_PT0.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_903_1_fsG.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_904_1_pgc.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_905_1_bsY.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_906_1_S9d.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_907_1_cxi.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_908_1_Zc8.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_909_1_u13.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_90_1_YGU.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_910_1_lsc.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_911_4_1Hi.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_912_1_bC4.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_913_1_vmA.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_914_1_DAA.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_915_3_I0H.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_916_1_Ykn.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_917_1_MJc.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_918_2_wL3.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_919_2_OPA.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_91_1_Q8Q.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_920_1_yhK.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_921_3_Aw4.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_922_1_Nbz.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_923_1_KwB.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_924_2_IuJ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_925_2_TUp.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_926_2_3JK.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_927_2_oHa.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_928_2_meo.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_929_2_pzC.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_92_1_BHQ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_930_1_0es.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_931_2_5Zf.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_932_2_lAu.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_933_2_fUt.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_934_2_9HG.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_935_2_AiH.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_936_2_2YK.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_937_2_TLi.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_938_3_Gdy.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_939_2_OLA.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_93_1_z7T.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_940_2_hym.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_941_2_PD8.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_942_2_F8S.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_943_2_yhZ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_944_2_U9T.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_945_2_gy1.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_946_2_QKL.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_947_2_TOH.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_948_2_pvc.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_949_3_7RM.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_94_1_sa3.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_950_2_Pd6.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_951_2_h88.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_952_2_wwo.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_953_2_xmj.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_954_2_2aW.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_955_2_5t7.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_956_2_JYQ.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_957_2_MDS.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_958_2_Deb.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_959_2_nqa.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_95_1_r0o.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_960_2_aLA.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_961_2_stp.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_962_3_BMW.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_963_2_RuW.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_964_3_lXN.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_965_2_AnK.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_966_2_Teg.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_967_3_UV1.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_968_2_utt.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_969_2_pkO.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_96_1_XB6.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_970_2_YXv.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_971_2_isG.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_972_2_nj5.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_973_2_qpf.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_974_3_d4n.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_975_2_jjL.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_976_3_b6A.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_977_3_x1I.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_978_3_DdP.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_979_3_EvV.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_97_1_h5L.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_980_3_DLD.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_981_3_nMa.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_982_3_59S.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_983_2_efu.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_984_3_Iiv.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_985_3_fUj.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_986_3_6d7.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_987_3_pzg.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_988_3_BSn.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_989_3_42G.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_98_1_24k.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_990_3_s5c.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_991_3_sEg.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_992_4_ePC.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_993_3_mEk.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_994_4_HQ4.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_995_3_NHv.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_996_3_BA6.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_997_3_0Ye.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_998_2_tmY.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_999_3_XTc.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_99_1_IiE.root',
##     'root://eoscms//eos/cms/store/user/friccita/WToMuNu_skim/Summer12_WJetsToLNu_WMuNuSkim_9_1_mu0.root'
##     ])
readFiles.extend([
    'file:/data1/yohay/NMSSMHiggs_WH_files1-250_24Sep12.root',
    'file:/data1/yohay/NMSSMHiggs_WH_files251-500_24Sep12.root',
    'file:/data1/yohay/NMSSMHiggs_WH_files501-750_24Sep12.root',
    'file:/data1/yohay/NMSSMHiggs_WH_files751-1000_24Sep12.root'
    ])

#for L1GtStableParametersRcd
process.load('Configuration/StandardSequences/FrontierConditions_GlobalTag_cff')
process.GlobalTag.globaltag = cms.string('START52_V9::All')

#for HLT selection
process.load('HLTrigger/HLTfilters/hltHighLevel_cfi')

#for mu-less jets
process.load("Configuration.StandardSequences.MagneticField_38T_cff")
process.load("Configuration.StandardSequences.GeometryExtended_cff")
process.load("RecoTauTag.Configuration.RecoPFTauTag_cff")
process.load("RecoTauTag.RecoTau.RecoTauPiZeroProducer_cfi")
process.load('BoostedTauAnalysis/CleanJets/cleanjets_cfi')

#define a parameter set to be passed to all modules that utilize GenTauDecayID for signal taus
commonGenTauDecayIDPSet = cms.PSet(momPDGID = cms.vint32(A_PDGID),
                                   chargedHadronPTMin = cms.double(0.0),
                                   neutralHadronPTMin = cms.double(0.0),
                                   chargedLeptonPTMin = cms.double(0.0),
                                   totalPTMin = cms.double(0.0))

#define a parameter set for the W-->munu selector
WMuNuPSet = commonGenTauDecayIDPSet.clone()
WMuNuPSet.momPDGID = cms.vint32(W_PDGID)

#define a parameter set for background W+jet jet-parton matching
WRecoilJetPSet = commonGenTauDecayIDPSet.clone()
WRecoilJetPSet.momPDGID = cms.vint32(ANY_PDGID)

#require event to fire IsoMu24_eta2p1
process.IsoMu24eta2p1Selector = process.hltHighLevel.clone()
process.IsoMu24eta2p1Selector.HLTPaths = cms.vstring('HLT_IsoMu24_eta2p1_v11')

#only proceed if event is a true W-->munu event
process.genWMuNuSelector = cms.EDFilter(
    'GenObjectProducer',
    genParticleTag = cms.InputTag('genParticles'),
    absMatchPDGIDs = cms.vuint32(MU_PDGID),
    sisterAbsMatchPDGID = cms.uint32(NUMU_PDGID),
    genTauDecayIDPSet = WMuNuPSet,
    primaryTauDecayType = cms.uint32(TAU_ALL),
    sisterTauDecayType = cms.uint32(TAU_ALL),
    primaryTauPTRank = cms.int32(ANY_PT_RANK),
    primaryTauHadronicDecayType = cms.int32(TAU_ALL_HAD),
    sisterHadronicDecayType = cms.int32(TAU_ALL_HAD),
    primaryTauAbsEtaMax = cms.double(-1.0),
    primaryTauPTMin = cms.double(-1.0),
    countSister = cms.bool(False),
    applyPTCuts = cms.bool(False),
    countKShort = cms.bool(True),
    minNumGenObjectsToPassFilter = cms.uint32(1),
    makeAllCollections = cms.bool(False)
    )

#clean the jets, then rebuild the taus
process.recoTauAK5PFJets08Region.src = cms.InputTag("CleanJets", "ak5PFJetsNoMu", "ANALYSIS")
process.ak5PFJetsRecoTauPiZeros.jetSrc = cms.InputTag("CleanJets", "ak5PFJetsNoMu", "ANALYSIS")
process.combinatoricRecoTaus.jetSrc = cms.InputTag("CleanJets", "ak5PFJetsNoMu", "ANALYSIS")
process.ak5PFJetTracksAssociatorAtVertex.jets = cms.InputTag("CleanJets", "ak5PFJetsNoMu",
                                                             "ANALYSIS")
process.ak5PFJetsLegacyHPSPiZeros.jetSrc = cms.InputTag("CleanJets", "ak5PFJetsNoMu", "ANALYSIS")
process.recoTauCommonSequence = cms.Sequence(process.CleanJets*
                                             process.ak5PFJetTracksAssociatorAtVertex*
                                             process.recoTauAK5PFJets08Region*
                                             process.recoTauPileUpVertices*
                                             process.pfRecoTauTagInfoProducer
                                             )
process.PFTau = cms.Sequence(process.recoTauCommonSequence*process.recoTauClassicHPSSequence)

#produce gen tau collection
process.genTauSelector = cms.EDFilter(
    'GenObjectProducer',
    genParticleTag = cms.InputTag('genParticles'),
    absMatchPDGIDs = cms.vuint32(TAU_PDGID),
    sisterAbsMatchPDGID = cms.uint32(TAU_PDGID),
    genTauDecayIDPSet = commonGenTauDecayIDPSet,
    primaryTauDecayType = cms.uint32(TAU_HAD),
    sisterTauDecayType = cms.uint32(TAU_MU),
    primaryTauPTRank = cms.int32(ANY_PT_RANK),
    primaryTauHadronicDecayType = cms.int32(TAU_ALL_HAD),
    sisterHadronicDecayType = cms.int32(TAU_ALL_HAD),
    primaryTauAbsEtaMax = cms.double(-1.0),
    primaryTauPTMin = cms.double(-1.0),
    countSister = cms.bool(False),
    applyPTCuts = cms.bool(False),
    countKShort = cms.bool(True),
    minNumGenObjectsToPassFilter = cms.uint32(1),
    makeAllCollections = cms.bool(False)
    )

#produce gen parton collection
process.genPartonSelector = cms.EDFilter(
    'GenPartonProducer',
    genParticleTag = cms.InputTag('genParticles'),
    partonAbsEtaMax = cms.double(-1.0),
    partonPTMin = cms.double(-1.0),
    minNumGenObjectsToPassFilter = cms.uint32(1)
    )

#produce AK5 PF jets
process.recoJetSelector = cms.EDFilter(
    'PFJetRefSelector',
    src = cms.InputTag('ak5PFJets'),
##     cut = cms.string('(pt > 20.0) && (abs(eta) < 2.4)'),
    cut = cms.string('abs(eta) < 2.4'),
    filter = cms.bool(True)
    )

#produce gen-matched AK5 PF jets
process.genMatchedRecoTauSelector = cms.EDFilter(
    'GenMatchedJetProducer',
    genParticleTag = cms.InputTag('genParticles'),
    selectedGenParticleTag = cms.InputTag('genTauSelector'),
##     selectedGenParticleTag = cms.InputTag('genPartonSelector'),
    recoObjTag = cms.InputTag('recoJetSelector'),
    baseRecoObjTag = cms.InputTag('ak5PFJets'),
    genTauDecayIDPSet = commonGenTauDecayIDPSet,
##     genTauDecayIDPSet = WRecoilJetPSet,
    applyPTCuts = cms.bool(False),
    countKShort = cms.bool(True),
    pTRank = cms.int32(ANY_PT_RANK),
    makeAllCollections = cms.bool(False),
    useGenObjPTRank = cms.bool(True),
    nOutputColls = cms.uint32(1),
    dR = cms.double(0.3),
    minNumGenObjectsToPassFilter = cms.uint32(1)
    )

#analyze gen-matched AK5 PF jets
process.analyzeJets = cms.EDAnalyzer(
    'JetAnalyzer',
##     outFileName = cms.string('/data1/yohay/WJetsToLNu_jet_analysis.root'),
##     outFileName = cms.string('/data1/yohay/debug.root'),
##     outFileName = cms.string('/data1/yohay/debug_signal.root'),
    outFileName = cms.string('/data1/yohay/Wh1_muon_jet_analysis.root'),
    textOutFileName = cms.string('/data1/yohay/Wh1_muon_jet_analysis.txt'),
    genTauDecayIDPSet = commonGenTauDecayIDPSet,
    applyPTCuts = cms.bool(False),
    countKShort = cms.bool(True),
    sisterAbsMatchPDGID = cms.uint32(TAU_PDGID),
##     jetTags = cms.VInputTag(cms.InputTag('genMatchedRecoTauSelector', 'coll0', 'ANALYSIS')),
    jetTags = cms.VInputTag('genMatchedRecoTauSelector'),
    METTag = cms.InputTag('pfMet'),
    genParticleTag = cms.InputTag('genParticles'),
##     selectedGenObjTag = cms.InputTag('genPartonSelector'),
    selectedGenObjTag = cms.InputTag('genTauSelector'),
    muonTag = cms.InputTag('muons'),
    dR = cms.double(0.3),
    pTRankColors = cms.vuint32(1, 2, 4, 6),
    pTRankStyles = cms.vuint32(20, 21, 22, 23),
    pTRankEntries = cms.vstring('Highest p_{T}', 'Second highest p_{T}', 'Third highest p_{T}',
                                'Lowest p_{T}')
    )

#path
## process.p = cms.Path(process.genWMuNuSelector*process.genPartonSelector*process.recoJetSelector*
##                      process.genMatchedRecoTauSelector*process.analyzeJets)
process.p = cms.Path(process.genWMuNuSelector*process.genTauSelector*process.recoJetSelector*
                     process.genMatchedRecoTauSelector*process.analyzeJets)
