ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of nmssm'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_195 = ', GC_195
      WRITE(*,2) 'GC_596 = ', GC_596
      WRITE(*,2) 'GC_623 = ', GC_623
      WRITE(*,2) 'GC_739 = ', GC_739
      WRITE(*,2) 'GC_1196 = ', GC_1196
